name: shotly
description: A mobile-first platform for peer-to-peer transactions of original digital content.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0
  google_generative_ai: ^0.4.7 # for Gemini models
  
  # State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6
  
  # UI Components
  flutter_animate: ^4.2.0
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.10.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.8
  file_picker: ^10.3.2
  video_player: ^2.7.0
  chewie: ^1.7.0
  flutter_svg: ^2.0.7
  lottie: ^3.3.1
  fl_chart: ^1.0.0
  
  # Navigation
  go_router: ^16.2.0
  introduction_screen: ^4.0.0
  
  # Utilities
  intl: ^0.20.2
  flutter_jailbreak_detection: ^1.10.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  path_provider: ^2.1.1
  uuid: ^4.2.2
  url_launcher: ^6.1.12
  share_plus: ^11.1.0
  http: ^1.1.0
  flutter_tts: ^4.0.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.1
  image: ^4.1.3  # For image processing and validation
  
  # Payment Processing
  in_app_purchase: ^3.1.8
  flutter_stripe: ^12.0.2
  
  # Analytics and Monitoring
  firebase_crashlytics: ^5.0.0
  
  # Authentication
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  
  # Storage and Caching
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image_web: ^1.3.1
  flutter_image_compress: ^2.0.4
  connectivity_plus: ^6.1.5
  
  # Localization
  # flutter_localizations is already included at the top of dependencies
  
  # Security
  visibility_detector: ^0.4.0+2
  flutter_windowmanager: ^0.2.0
  dio: ^5.4.0  # HTTP client with pinning support
  flutter_secure_storage: ^10.0.0-beta.4  # For secure encrypted storage
  asn1lib: ^1.6.5  # Using older version for Uint8List compatibility
dependency_overrides:
  image_picker_platform_interface: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2
  mockito: ^5.4.2
  firebase_core_platform_interface: ^6.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/lang/
  
  # Using Google Fonts for web platform
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700