allprojects {
    repositories {
        // Google's Maven repository for all subprojects
        google()
        // Maven Central repository for all subprojects
        mavenCentral()
    }
}

// Sets the root build directory for all project outputs
rootProject.buildDir = '../build'

// Configures each subproject to use a build directory within the root build directory
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// Defines a 'clean' task to delete the entire build directory
tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
