// Top-level build file where you can add configuration options common to all sub-projects/modules. 
 buildscript { 
     ext.kotlin_version = '2.1.0' 
     ext.java_version = JavaVersion.VERSION_17 
 
     repositories { 
         // Google's Maven repository 
         google() 
         // The Maven Central repository 
         mavenCentral() 
     } 
 
     dependencies {
        // Google Services plugin (for Firebase)
        classpath 'com.google.gms:google-services:4.4.3'
        // Firebase Crashlytics Gradle plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    } 
 } 
 
 plugins { 
    // Defines the Android Application plugin. 
    // The `apply false` is crucial here so that the plugin is only applied to modules 
    // that explicitly need it (e.g., the app module). 
    id 'com.android.application' apply false 

    // Defines the Android Library plugin. 
    // The `apply false` is used for the same reason as above. 
    id 'com.android.library' apply false 

    // Defines the Kotlin Android plugin. 
    id 'org.jetbrains.kotlin.android' apply false 
} 
 
 // Configures repositories for all projects (including the root project and all subprojects). 
 allprojects { 
     repositories { 
         // Google's Maven repository, required for Android-specific libraries. 
         google() 
 
         // The Maven Central repository, a common source for many libraries. 
         mavenCentral() 
     } 
 } 
 
 // Defines a 'clean' task to delete the entire build directory of the root project. 
 // This is a standard and useful task for cleaning up generated files. 
 tasks.register("clean", Delete) { 
     delete rootProject.buildDir 
 }
